dist: bionic

language: c++

before_install:
  - sudo apt-get -y install qt5-qmake qtbase5-dev qtconnectivity5-dev qtdeclarative5-dev qtquickcontrols2-5-dev qml-module-qtquick-controls

script:
- mkdir build && cd build && qmake -qt=qt5 -makefile -o Makefile "CONFIG+=telescope" ../asteroidsyncservice.pro && make
